# coding: utf-8

"""
    Product Partner API

    Product Partner APIs can create, list, and modify goals, prds, status updates, and other product management artifacts.

    The version of the OpenAPI document: v1
    Contact: info@productpartner.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pp_sdk.models.template_section import TemplateSection

class TestTemplateSection(unittest.TestCase):
    """TemplateSection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TemplateSection:
        """Test TemplateSection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemplateSection`
        """
        model = TemplateSection()
        if include_optional:
            return TemplateSection(
                id = '',
                template = '',
                section = '',
                order = -2147483648,
                created_by = pp_sdk.models.user_field.User Field(
                    id = '', 
                    email = '', 
                    first_name = '', 
                    last_name = '', ),
                created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                deleted = True
            )
        else:
            return TemplateSection(
                template = '',
                section = '',
        )
        """

    def testTemplateSection(self):
        """Test TemplateSection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
