# coding: utf-8

"""
    Product Partner API

    Product Partner APIs can create, list, and modify goals, prds, status updates, and other product management artifacts.

    The version of the OpenAPI document: v1
    Contact: chris@productpartner.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pp_sdk.api.chat_api import ChatApi


class TestChatApi(unittest.TestCase):
    """ChatApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ChatApi()

    def tearDown(self) -> None:
        pass

    def test_chat(self) -> None:
        """Test case for chat

        """
        pass

    def test_chat_history(self) -> None:
        """Test case for chat_history

        """
        pass

    def test_chat_upload_file(self) -> None:
        """Test case for chat_upload_file

        """
        pass


if __name__ == '__main__':
    unittest.main()
