# coding: utf-8

"""
    Product Partner API

    Product Partner APIs can create, list, and modify goals, prds, status updates, and other product management artifacts.

    The version of the OpenAPI document: v1
    Contact: info@productpartner.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pp_sdk.models.organization_setup import OrganizationSetup

class TestOrganizationSetup(unittest.TestCase):
    """OrganizationSetup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationSetup:
        """Test OrganizationSetup
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationSetup`
        """
        model = OrganizationSetup()
        if include_optional:
            return OrganizationSetup(
                id = '',
                organization = '',
                project_system_setup_state = 'NOT_STARTED',
                repo_setup_state = 'NOT_STARTED',
                document_setup_state = 'NOT_STARTED',
                retro_setup_state = 'NOT_STARTED',
                users_setup_state = 'NOT_STARTED',
                company_setup_state = 'NOT_STARTED',
                setup_complete = True
            )
        else:
            return OrganizationSetup(
        )
        """

    def testOrganizationSetup(self):
        """Test OrganizationSetup"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
