# coding: utf-8

"""
    Product Partner API

    Product Partner APIs can create, list, and modify goals, prds, status updates, and other product management artifacts.

    The version of the OpenAPI document: v1
    Contact: chris@productpartner.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pp_sdk.models.api_userstories_create_request import ApiUserstoriesCreateRequest

class TestApiUserstoriesCreateRequest(unittest.TestCase):
    """ApiUserstoriesCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiUserstoriesCreateRequest:
        """Test ApiUserstoriesCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiUserstoriesCreateRequest`
        """
        model = ApiUserstoriesCreateRequest()
        if include_optional:
            return ApiUserstoriesCreateRequest(
                prd = '',
                as_a = '',
                i_want_to = '',
                so_that = '',
                freetext_override = '',
                due_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = 'RED',
                priority = '',
                tags = [
                    ''
                    ]
            )
        else:
            return ApiUserstoriesCreateRequest(
                prd = '',
        )
        """

    def testApiUserstoriesCreateRequest(self):
        """Test ApiUserstoriesCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
