# coding: utf-8

"""
    Product Partner API

    Product Partner APIs can create, list, and modify goals, prds, status updates, and other product management artifacts.

    The version of the OpenAPI document: v1
    Contact: chris@productpartner.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pp_sdk.api.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()

    def tearDown(self) -> None:
        pass

    def test_users_create(self) -> None:
        """Test case for users_create

        """
        pass

    def test_users_delete(self) -> None:
        """Test case for users_delete

        """
        pass

    def test_users_list(self) -> None:
        """Test case for users_list

        """
        pass

    def test_users_partial_update(self) -> None:
        """Test case for users_partial_update

        """
        pass

    def test_users_picker_list(self) -> None:
        """Test case for users_picker_list

        """
        pass

    def test_users_read(self) -> None:
        """Test case for users_read

        """
        pass

    def test_users_update(self) -> None:
        """Test case for users_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
