# coding: utf-8

"""
    Product Partner API

    Product Partner APIs can create, list, and modify goals, prds, status updates, and other product management artifacts.

    The version of the OpenAPI document: v1
    Contact: chris@productpartner.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.api_api import ApiApi


class TestApiApi(unittest.TestCase):
    """ApiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApiApi()

    def tearDown(self) -> None:
        pass

    def test_api_goals_create(self) -> None:
        """Test case for api_goals_create

        """
        pass

    def test_api_goals_delete(self) -> None:
        """Test case for api_goals_delete

        """
        pass

    def test_api_goals_list(self) -> None:
        """Test case for api_goals_list

        """
        pass

    def test_api_goals_partial_update(self) -> None:
        """Test case for api_goals_partial_update

        """
        pass

    def test_api_goals_read(self) -> None:
        """Test case for api_goals_read

        """
        pass

    def test_api_goals_update(self) -> None:
        """Test case for api_goals_update

        """
        pass

    def test_api_prds_create(self) -> None:
        """Test case for api_prds_create

        """
        pass

    def test_api_prds_delete(self) -> None:
        """Test case for api_prds_delete

        """
        pass

    def test_api_prds_list(self) -> None:
        """Test case for api_prds_list

        """
        pass

    def test_api_prds_partial_update(self) -> None:
        """Test case for api_prds_partial_update

        """
        pass

    def test_api_prds_read(self) -> None:
        """Test case for api_prds_read

        """
        pass

    def test_api_prds_update(self) -> None:
        """Test case for api_prds_update

        """
        pass

    def test_api_status_create(self) -> None:
        """Test case for api_status_create

        """
        pass

    def test_api_status_delete(self) -> None:
        """Test case for api_status_delete

        """
        pass

    def test_api_status_list(self) -> None:
        """Test case for api_status_list

        """
        pass

    def test_api_status_partial_update(self) -> None:
        """Test case for api_status_partial_update

        """
        pass

    def test_api_status_read(self) -> None:
        """Test case for api_status_read

        """
        pass

    def test_api_status_update(self) -> None:
        """Test case for api_status_update

        """
        pass

    def test_api_user_create_create(self) -> None:
        """Test case for api_user_create_create

        """
        pass

    def test_api_user_read(self) -> None:
        """Test case for api_user_read

        """
        pass

    def test_api_user_search_list(self) -> None:
        """Test case for api_user_search_list

        """
        pass

    def test_api_user_update_partial_update(self) -> None:
        """Test case for api_user_update_partial_update

        """
        pass

    def test_api_user_update_update(self) -> None:
        """Test case for api_user_update_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
