# coding: utf-8

"""
    Product Partner API

    Product Partner APIs can create, list, and modify goals, prds, status updates, and other product management artifacts.

    The version of the OpenAPI document: v1
    Contact: chris@productpartner.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from pp_sdk.models.api_goals_picker_list200_response import ApiGoalsPickerList200Response  # noqa: E501

class TestApiGoalsPickerList200Response(unittest.TestCase):
    """ApiGoalsPickerList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiGoalsPickerList200Response:
        """Test ApiGoalsPickerList200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiGoalsPickerList200Response`
        """
        model = ApiGoalsPickerList200Response()  # noqa: E501
        if include_optional:
            return ApiGoalsPickerList200Response(
                count = 56,
                next = '',
                previous = '',
                results = [
                    pp_sdk.models.goal_picker.GoalPicker(
                        id = '', 
                        name = '0', 
                        goal_language = '0', )
                    ]
            )
        else:
            return ApiGoalsPickerList200Response(
                count = 56,
                results = [
                    pp_sdk.models.goal_picker.GoalPicker(
                        id = '', 
                        name = '0', 
                        goal_language = '0', )
                    ],
        )
        """

    def testApiGoalsPickerList200Response(self):
        """Test ApiGoalsPickerList200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
