# coding: utf-8

"""
    Product Partner API

    Product Partner APIs can create, list, and modify goals, prds, status updates, and other product management artifacts.

    The version of the OpenAPI document: v1
    Contact: info@productpartner.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pp_sdk.api.goals_api import GoalsApi


class TestGoalsApi(unittest.TestCase):
    """GoalsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GoalsApi()

    def tearDown(self) -> None:
        pass

    def test_goals_create(self) -> None:
        """Test case for goals_create

        """
        pass

    def test_goals_delete(self) -> None:
        """Test case for goals_delete

        """
        pass

    def test_goals_list(self) -> None:
        """Test case for goals_list

        """
        pass

    def test_goals_partial_update(self) -> None:
        """Test case for goals_partial_update

        """
        pass

    def test_goals_picker_list(self) -> None:
        """Test case for goals_picker_list

        """
        pass

    def test_goals_read(self) -> None:
        """Test case for goals_read

        """
        pass

    def test_goals_update(self) -> None:
        """Test case for goals_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
