# coding: utf-8

# flake8: noqa
"""
    Product Partner API

    Product Partner APIs can create, list, and modify goals, prds, status updates, and other product management artifacts.

    The version of the OpenAPI document: v1
    Contact: chris@productpartner.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from pp_sdk.models.address import Address
from pp_sdk.models.api_goals_picker_list200_response_inner import ApiGoalsPickerList200ResponseInner
from pp_sdk.models.goal import Goal
from pp_sdk.models.goal_base import GoalBase
from pp_sdk.models.organization import Organization
from pp_sdk.models.prd import PRD
from pp_sdk.models.prd_template import PRDTemplate
from pp_sdk.models.program import Program
from pp_sdk.models.program_picker import ProgramPicker
from pp_sdk.models.status import Status
from pp_sdk.models.tag import Tag
from pp_sdk.models.user import User
from pp_sdk.models.user_story import UserStory
