# coding: utf-8

"""
    Product Partner API

    Product Partner APIs can create, list, and modify goals, prds, status updates, and other product management artifacts.

    The version of the OpenAPI document: v1
    Contact: chris@productpartner.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from pp_sdk.models.created_by import CreatedBy
from pp_sdk.models.owner_users_inner import OwnerUsersInner
from pp_sdk.models.programs_inner import ProgramsInner
from pp_sdk.models.tags_inner import TagsInner
from typing import Optional, Set
from typing_extensions import Self

class Goal(BaseModel):
    """
    Goal
    """ # noqa: E501
    id: Optional[StrictStr] = None
    name: Annotated[str, Field(min_length=1, strict=True, max_length=255)]
    goal_language: Annotated[str, Field(min_length=1, strict=True)]
    description: Optional[StrictStr] = None
    why_it_matters: Optional[StrictStr] = None
    created_date: Optional[datetime] = None
    modified_date: Optional[datetime] = None
    original_due_date: Optional[datetime] = None
    current_due_date: Optional[datetime] = None
    owner_users: Optional[List[OwnerUsersInner]] = None
    programs: Optional[List[ProgramsInner]] = None
    stakeholder_users: Optional[List[OwnerUsersInner]] = None
    tags: Optional[List[TagsInner]] = None
    version: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    version_summary: Optional[StrictStr] = None
    created_by: Optional[CreatedBy] = None
    status: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "name", "goal_language", "description", "why_it_matters", "created_date", "modified_date", "original_due_date", "current_due_date", "owner_users", "programs", "stakeholder_users", "tags", "version", "version_summary", "created_by", "status"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Goal from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "created_date",
            "modified_date",
            "owner_users",
            "programs",
            "stakeholder_users",
            "tags",
            "status",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in owner_users (list)
        _items = []
        if self.owner_users:
            for _item in self.owner_users:
                if _item:
                    _items.append(_item.to_dict())
            _dict['owner_users'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in programs (list)
        _items = []
        if self.programs:
            for _item in self.programs:
                if _item:
                    _items.append(_item.to_dict())
            _dict['programs'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in stakeholder_users (list)
        _items = []
        if self.stakeholder_users:
            for _item in self.stakeholder_users:
                if _item:
                    _items.append(_item.to_dict())
            _dict['stakeholder_users'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item in self.tags:
                if _item:
                    _items.append(_item.to_dict())
            _dict['tags'] = _items
        # override the default output from pydantic by calling `to_dict()` of created_by
        if self.created_by:
            _dict['created_by'] = self.created_by.to_dict()
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if why_it_matters (nullable) is None
        # and model_fields_set contains the field
        if self.why_it_matters is None and "why_it_matters" in self.model_fields_set:
            _dict['why_it_matters'] = None

        # set to None if version (nullable) is None
        # and model_fields_set contains the field
        if self.version is None and "version" in self.model_fields_set:
            _dict['version'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Goal from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "goal_language": obj.get("goal_language"),
            "description": obj.get("description"),
            "why_it_matters": obj.get("why_it_matters"),
            "created_date": obj.get("created_date"),
            "modified_date": obj.get("modified_date"),
            "original_due_date": obj.get("original_due_date"),
            "current_due_date": obj.get("current_due_date"),
            "owner_users": [OwnerUsersInner.from_dict(_item) for _item in obj["owner_users"]] if obj.get("owner_users") is not None else None,
            "programs": [ProgramsInner.from_dict(_item) for _item in obj["programs"]] if obj.get("programs") is not None else None,
            "stakeholder_users": [OwnerUsersInner.from_dict(_item) for _item in obj["stakeholder_users"]] if obj.get("stakeholder_users") is not None else None,
            "tags": [TagsInner.from_dict(_item) for _item in obj["tags"]] if obj.get("tags") is not None else None,
            "version": obj.get("version"),
            "version_summary": obj.get("version_summary"),
            "created_by": CreatedBy.from_dict(obj["created_by"]) if obj.get("created_by") is not None else None,
            "status": obj.get("status")
        })
        return _obj


