# coding: utf-8

"""
    Product Partner API

    Product Partner APIs can create, list, and modify goals, prds, status updates, and other product management artifacts.

    The version of the OpenAPI document: v1
    Contact: chris@productpartner.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field, StrictStr, constr

class Program(BaseModel):
    """
    Program
    """
    id: Optional[StrictStr] = None
    name: constr(strict=True, max_length=255, min_length=1) = Field(...)
    description: Optional[StrictStr] = None
    charter: Optional[StrictStr] = None
    principal_users: Optional[StrictStr] = None
    stakeholder_users: Optional[StrictStr] = None
    parent: Optional[StrictStr] = None
    tags: Optional[StrictStr] = None
    created_by: Optional[StrictStr] = None
    created_date: Optional[datetime] = None
    modified_date: Optional[datetime] = None
    additional_properties: Dict[str, Any] = {}
    __properties = ["id", "name", "description", "charter", "principal_users", "stakeholder_users", "parent", "tags", "created_by", "created_date", "modified_date"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Program:
        """Create an instance of Program from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "id",
                            "principal_users",
                            "stakeholder_users",
                            "tags",
                            "created_by",
                            "created_date",
                            "modified_date",
                            "additional_properties"
                          },
                          exclude_none=True)
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if description (nullable) is None
        # and __fields_set__ contains the field
        if self.description is None and "description" in self.__fields_set__:
            _dict['description'] = None

        # set to None if charter (nullable) is None
        # and __fields_set__ contains the field
        if self.charter is None and "charter" in self.__fields_set__:
            _dict['charter'] = None

        # set to None if parent (nullable) is None
        # and __fields_set__ contains the field
        if self.parent is None and "parent" in self.__fields_set__:
            _dict['parent'] = None

        # set to None if created_date (nullable) is None
        # and __fields_set__ contains the field
        if self.created_date is None and "created_date" in self.__fields_set__:
            _dict['created_date'] = None

        # set to None if modified_date (nullable) is None
        # and __fields_set__ contains the field
        if self.modified_date is None and "modified_date" in self.__fields_set__:
            _dict['modified_date'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Program:
        """Create an instance of Program from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Program.parse_obj(obj)

        _obj = Program.parse_obj({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "charter": obj.get("charter"),
            "principal_users": obj.get("principal_users"),
            "stakeholder_users": obj.get("stakeholder_users"),
            "parent": obj.get("parent"),
            "tags": obj.get("tags"),
            "created_by": obj.get("created_by"),
            "created_date": obj.get("created_date"),
            "modified_date": obj.get("modified_date")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


