# coding: utf-8

"""
    Product Partner API

    Product Partner APIs can create, list, and modify goals, prds, status updates, and other product management artifacts.

    The version of the OpenAPI document: v1
    Contact: info@productpartner.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from pp_sdk.models.section_context import SectionContext
from pp_sdk.models.user_field import UserField
from typing import Optional, Set
from typing_extensions import Self

class Section(BaseModel):
    """
    Section
    """ # noqa: E501
    id: Optional[StrictStr] = None
    name: Annotated[str, Field(min_length=1, strict=True, max_length=255)]
    prompt: Annotated[str, Field(min_length=1, strict=True)]
    target_model: Optional[StrictStr] = None
    user_instructions: Optional[StrictStr] = None
    examples: Optional[List[StrictStr]] = None
    section_contexts: Optional[List[SectionContext]] = None
    organization: Optional[StrictStr] = None
    created_by: Optional[UserField] = None
    created_date: Optional[datetime] = None
    modified_date: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["id", "name", "prompt", "target_model", "user_instructions", "examples", "section_contexts", "organization", "created_by", "created_date", "modified_date"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Section from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "section_contexts",
            "organization",
            "created_date",
            "modified_date",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in section_contexts (list)
        _items = []
        if self.section_contexts:
            for _item_section_contexts in self.section_contexts:
                if _item_section_contexts:
                    _items.append(_item_section_contexts.to_dict())
            _dict['section_contexts'] = _items
        # override the default output from pydantic by calling `to_dict()` of created_by
        if self.created_by:
            _dict['created_by'] = self.created_by.to_dict()
        # set to None if target_model (nullable) is None
        # and model_fields_set contains the field
        if self.target_model is None and "target_model" in self.model_fields_set:
            _dict['target_model'] = None

        # set to None if user_instructions (nullable) is None
        # and model_fields_set contains the field
        if self.user_instructions is None and "user_instructions" in self.model_fields_set:
            _dict['user_instructions'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Section from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "prompt": obj.get("prompt"),
            "target_model": obj.get("target_model"),
            "user_instructions": obj.get("user_instructions"),
            "examples": obj.get("examples"),
            "section_contexts": [SectionContext.from_dict(_item) for _item in obj["section_contexts"]] if obj.get("section_contexts") is not None else None,
            "organization": obj.get("organization"),
            "created_by": UserField.from_dict(obj["created_by"]) if obj.get("created_by") is not None else None,
            "created_date": obj.get("created_date"),
            "modified_date": obj.get("modified_date")
        })
        return _obj


